
CREATE TABLE public.bon (
	bon_id bigserial NOT NULL,
	bon_date date NULL,
	bon_time time NULL,
	store_no text NULL,
	transaction_no text NULL,
	pos_code text NULL,
	total_gross numeric NULL,
	total_nett numeric NULL,
	total_payment numeric NULL,
	cashier_id text NULL,
	loyalty_member text NULL,
	loyalty_id text NULL,
	loyalty_name text NULL,
	transaction_type text NULL,
	transaction_status text NULL,
	transaction_flag text NULL,
	cancel_transaction_no text NULL,
	deposit_transaction_no text NULL,
	flag char(1),
	site_code text NULL,
	channel text NULL,
	timestamp timestamp,
	CONSTRAINT bon_pk PRIMARY KEY (bon_id)
);